# Generated by Django 5.2.7 on 2025-10-27 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='direccion_cliente',
            new_name='direccion_entrega',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'cliente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_cliente', to='gestionPedidos.usuario'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mesero',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'mesero'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_mesero', to='gestionPedidos.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('mesero', 'Mesero'), ('cocinero', 'Cocinero'), ('cajero', 'Cajero'), ('cliente', 'Cliente')], max_length=20),
        ),
    ]
