# Generated by Django 5.2.7 on 2025-11-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0003_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('en preparacion', 'En preparación'), ('listo', 'Listo'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
    ]
