# Generated by Django 5.2.7 on 2025-11-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0005_detallepedido_precio_unitario_detallepedido_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='observacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
