# Generated by Django 5.2.7 on 2025-11-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0006_detallepedido_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='recargo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
