# Generated by Django 5.2.7 on 2025-11-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0007_detallepedido_recargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('en_creacion', 'En creación'), ('en preparacion', 'En preparación'), ('listo', 'Listo'), ('entregado', 'Entregado')], default='en_creacion', max_length=20),
        ),
    ]
