# Generated by Django 5.2.7 on 2025-11-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0009_auto_20251112_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cambio_password',
            field=models.BooleanField(default=False),
        ),
    ]
