# Generated by Django 5.2.7 on 2025-11-19 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0010_usuario_cambio_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
