# Generated by Django 5.2.7 on 2025-11-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0011_remove_mesa_estado_remove_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('en_creacion', 'En creación'), ('en preparacion', 'En preparación'), ('listo', 'Listo')], default='en_creacion', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('mesero', 'Mesero'), ('cocinero', 'Cocinero'), ('cajero', 'Cajero')], max_length=20),
        ),
    ]
