# Generated by Django 5.2.7 on 2025-11-22 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0012_alter_pedido_estado_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cajero',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'cajero'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_cajero', to=settings.AUTH_USER_MODEL),
        ),
    ]
