# Generated by Django 5.2.7 on 2025-11-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0013_pedido_cajero'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='estado',
            field=models.CharField(choices=[('libre', 'Libre'), ('ocupada', 'Ocupada')], default='libre', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('en_creacion', 'En creación'), ('en preparacion', 'En preparación'), ('listo', 'Listo'), ('entregado', 'Entregado'), ('finalizado', 'Finalizado')], default='en_creacion', max_length=20),
        ),
    ]
