# Generated by Django 5.2.7 on 2025-11-23 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0015_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.pedido'),
        ),
    ]
