# Generated by Django 5.2.7 on 2025-12-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0016_notificacion_mensaje_alter_notificacion_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
