# Generated by Django 5.2.7 on 2025-12-04 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0017_pedido_nombre_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='recargo_domicilio',
        ),
    ]
