# Generated by Django 5.2.7 on 2025-12-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0018_remove_pedido_recargo_domicilio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobante',
            name='tipo_comprobante',
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('en_creacion', 'En creación'), ('en preparacion', 'En preparación'), ('listo', 'Listo'), ('finalizado', 'Finalizado'), ('pagado', 'Pagado')], default='en_creacion', max_length=20),
        ),
    ]
