# Generated by Django 5.2.7 on 2025-12-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0020_pago_cambio_pago_monto_recibido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('en_creacion', 'En creación'), ('en preparacion', 'En preparación'), ('listo', 'Listo'), ('finalizado', 'Finalizado')], default='en_creacion', max_length=20),
        ),
    ]
