# Generated by Django 5.2.7 on 2025-12-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0022_alter_pago_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_creacion', 'En creación'), ('en preparacion', 'En preparación'), ('listo', 'Listo'), ('finalizado', 'Finalizado')], default='en_creacion', max_length=20),
        ),
    ]
