# Generated by Django 5.2.7 on 2025-12-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0023_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_pedido',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
