# Generated by Django 5.2.7 on 2025-12-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0024_pedido_codigo_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='codigo_pedido',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
