# Generated by Django 5.2.7 on 2025-12-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0025_alter_pedido_codigo_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
    ]
