# Generated by Django 5.2.7 on 2026-01-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0028_usuario_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='horario',
            field=models.CharField(blank=True, choices=[('lv_manana', 'L-V Mañana (06:00 - 14:00)'), ('lv_tarde', 'L-V Tarde (14:00 - 22:00)'), ('lv_noche', 'L-V Noche (22:00 - 06:00)'), ('sab_manana', 'Sábado Mañana (06:00 - 12:00)'), ('sab_tarde', 'Sábado Tarde (11:00 - 15:00)'), ('dom_unico', 'Domingo Único (06:00 - 13:00)')], max_length=20, null=True),
        ),
    ]
