# Generated by Django 5.2.7 on 2026-01-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0029_alter_usuario_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='enviado_cocina',
            field=models.BooleanField(default=False),
        ),
    ]
