# Generated by Django 5.2.7 on 2026-01-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0030_pedido_enviado_cocina'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='agotado_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='agotado_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
