# Generated by Django 5.2.7 on 2026-01-16 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0031_producto_agotado_fecha_producto_agotado_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cocinero_listo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_marcados_listos', to=settings.AUTH_USER_MODEL),
        ),
    ]
