# Generated by Django 5.2.7 on 2026-01-16 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0032_remove_pedido_cliente_pedido_cocinero_listo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='codigo_pedido',
        ),
    ]
