# Generated by Django 5.2.7 on 2026-01-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0033_remove_pedido_codigo_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_pedido',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
