# Generated by Django 5.2.7 on 2026-01-16 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0034_pedido_codigo_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cocinero_listo',
        ),
    ]
