# Generated by Django 5.2.7 on 2026-01-16 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0035_remove_pedido_cocinero_listo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'cliente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_cliente', to=settings.AUTH_USER_MODEL),
        ),
    ]
