# Generated by Django 5.2.7 on 2026-01-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0037_horario_alter_usuario_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='nombre',
            field=models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=100),
        ),
    ]
