# Generated by Django 5.2.7 on 2026-01-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0038_alter_horario_codigo_alter_horario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='dias',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='horario',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
