# Generated by Django 5.2.7 on 2026-01-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0040_alter_usuario_rol_comprobantecliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_creacion', 'En creación'), ('pendiente_caja', 'Pendiente de caja'), ('aceptado', 'Aceptado'), ('en preparacion', 'En preparación'), ('listo', 'Listo'), ('finalizado', 'Finalizado')], default='en_creacion', max_length=20),
        ),
    ]
