# Generated by Django 5.2.7 on 2026-03-05 23:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0043_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='archivo_pdf',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
