# Generated by Django 5.2.7 on 2026-03-05 23:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0044_alter_comprobante_archivo_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantecliente',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
