# Generated by Django 5.2.7 on 2026-03-05 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0045_alter_comprobantecliente_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='gestionPedidos.pago'),
        ),
    ]
